title: SimCity 4 Locales
description: Multilingual SimCityLocale.dat archives for SimCity 4 Deluxe v1.1.610
exclude:
  - "*.BAK"
  - ".bkp/"
  - ".ignore/"
  - ".tools/"
  - "Danish/"
  - "Dutch/"
  - "English/"
  - "Finnish/"
  - "Fonts/"
  - "French/"
  - "German/"
  - "Italian/"
  - "Norwgian/"
  - "Polish/"
  - "Portgese/"
  - "ReadMe/"
  - "Spanish/"
  - "Support/"
  - "Swedish/"
  - "UKEnglsh/"
  - "*.DAT"
  - "*.dat"
